version: '2.1'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:1.10.2
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - /home/ec2-user/docker-airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /home/ec2-user/docker-airflow/dags:/usr/local/airflow/dags
            - /home/ec2-user/docker-airflow/script/entrypoint.sh:/entrypoint.sh
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow:1.10.2
        restart: always
        depends_on:
            - postgres
            - redis
        volumes:
            - /home/ec2-user/docker-airflow/script/entrypoint.sh:/entrypoint.sh
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.10.2
        restart: always
        depends_on:
            - webserver
        volumes:
            - /home/ec2-user/docker-airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /home/ec2-user/docker-airflow/dags:/usr/local/airflow/dags
            - /home/ec2-user/docker-airflow/script/entrypoint.sh:/entrypoint.sh
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        command: scheduler

    worker:
        image: puckel/docker-airflow:1.10.2
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /home/ec2-user/docker-airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /home/ec2-user/docker-airflow/dags:/usr/local/airflow/dags
            - /home/ec2-user/docker-airflow/script/entrypoint.sh:/entrypoint.sh
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        command: worker
